// UGC Sri Lanka Course Database
export interface UGCCourse {
    courseName: string;
    university: string;
    uniCode: string;
    requiresAptitudeTest: boolean;
    eligibleStreams: string[];
    interestMapping: string[];
}

// Courses requiring aptitude tests
const aptitudeTestCodes = new Set([
    '020S', '041S', '023G', '024G', '034G', '068C', '068E', '068Y', '068Z',
    '069E', '069Y', '069Z', '070E', '071Y', '071Z', '072Y', '081E', '081L',
    '082C', '082D', '082L', '085Z', '097G', '100D'
]);

// Interest mapping for courses (q1-q12)
const courseInterestMap: Record<string, string[]> = {
    'MEDICINE': ['q2_healthcare', 'q9_innovation'],
    'DENTAL SURGERY': ['q2_healthcare', 'q8_hands_on'],
    'VETERINARY SCIENCE': ['q2_healthcare', 'q7_nature_env'],
    'AGRICULTURE': ['q7_nature_env', 'q8_hands_on'],
    'FOOD SCIENCE': ['q7_nature_env', 'q2_healthcare', 'q9_innovation'],
    'BIOLOGICAL SCIENCE': ['q1_science_tech', 'q2_healthcare', 'q7_nature_env'],
    'APPLIED SCIENCES (BIOLOGICAL': ['q1_science_tech', 'q2_healthcare', 'q7_nature_env'],
    'ENGINEERING': ['q1_science_tech', 'q8_hands_on', 'q9_innovation'],
    'QUANTITY SURVEYING': ['q11_urban_corporate', 'q4_data', 'q8_hands_on'],
    'COMPUTER SCIENCE': ['q1_science_tech', 'q4_data', 'q9_innovation'],
    'PHYSICAL SCIENCE': ['q1_science_tech', 'q4_data'],
    'SURVEYING': ['q11_urban_corporate', 'q8_hands_on'],
    'APPLIED SCIENCES (PHYSICAL': ['q1_science_tech', 'q4_data'],
    'MANAGEMENT': ['q5_business', 'q10_people_social', 'q11_urban_corporate'],
    'REAL ESTATE': ['q5_business', 'q11_urban_corporate'],
    'COMMERCE': ['q5_business', 'q4_data'],
    'ARTS': ['q6_arts_culture', 'q10_people_social'],
    'LAW': ['q10_people_social', 'q5_business'],
    'INFORMATION TECHNOLOGY': ['q1_science_tech', 'q4_data', 'q9_innovation'],
    'DESIGN': ['q3_design', 'q6_arts_culture', 'q9_innovation'],
    'ARCHITECTURE': ['q3_design', 'q1_science_tech', 'q11_urban_corporate'],
    'URBAN': ['q11_urban_corporate', 'q3_design'],
    'PEACE AND CONFLICT': ['q10_people_social', 'q6_arts_culture'],
    'AYURVEDA': ['q2_healthcare', 'q7_nature_env'],
    'UNANI': ['q2_healthcare', 'q7_nature_env'],
    'FASHION': ['q3_design', 'q6_arts_culture', 'q9_innovation'],
    'SIDDHA': ['q2_healthcare', 'q7_nature_env'],
    'NURSING': ['q2_healthcare', 'q10_people_social'],
    'ICT': ['q1_science_tech', 'q4_data', 'q9_innovation'],
    'HEALTH PROMOTION': ['q2_healthcare', 'q10_people_social'],
    'PHARMACY': ['q2_healthcare', 'q1_science_tech'],
    'MEDICAL LABORATORY': ['q2_healthcare', 'q8_hands_on', 'q1_science_tech'],
    'RADIOGRAPHY': ['q2_healthcare', 'q1_science_tech'],
    'PHYSIOTHERAPY': ['q2_healthcare', 'q8_hands_on'],
    'ENVIRONMENTAL': ['q7_nature_env', 'q1_science_tech'],
    'FACILITIES MANAGEMENT': ['q11_urban_corporate', 'q5_business'],
    'TRANSPORT': ['q11_urban_corporate', 'q5_business', 'q9_innovation'],
    'BIOCHEMISTRY': ['q1_science_tech', 'q2_healthcare', 'q9_innovation'],
    'STATISTICS': ['q4_data', 'q1_science_tech'],
    'FISHERIES': ['q7_nature_env', 'q8_hands_on'],
    'ISLAMIC STUDIES': ['q6_arts_culture', 'q10_people_social'],
    'SCIENCE AND TECHNOLOGY': ['q1_science_tech', 'q9_innovation'],
    'ENTREPRENEURSHIP': ['q5_business', 'q9_innovation', 'q12_flexible_path'],
    'ANIMAL': ['q7_nature_env', 'q2_healthcare'],
    'MUSIC': ['q6_arts_culture', 'q12_flexible_path'],
    'DANCE': ['q6_arts_culture', 'q12_flexible_path'],
    'ART & DESIGN': ['q3_design', 'q6_arts_culture'],
    'DRAMA': ['q6_arts_culture', 'q10_people_social'],
    'VISUAL': ['q3_design', 'q6_arts_culture'],
    'EXPORT AGRICULTURE': ['q7_nature_env', 'q5_business'],
    'MINERAL RESOURCES': ['q1_science_tech', 'q7_nature_env'],
    'BUSINESS INFORMATION': ['q4_data', 'q5_business'],
    'PHYSICAL EDUCATION': ['q8_hands_on', 'q10_people_social'],
    'SPORTS': ['q8_hands_on', 'q10_people_social', 'q5_business'],
    'SPEECH AND HEARING': ['q2_healthcare', 'q10_people_social'],
    'ARABIC': ['q6_arts_culture', 'q10_people_social'],
    'AQUATIC': ['q7_nature_env', 'q1_science_tech'],
    'HOSPITALITY': ['q12_flexible_path', 'q5_business', 'q10_people_social'],
    'TOURISM': ['q12_flexible_path', 'q5_business', 'q10_people_social'],
    'AGRIBUSINESS': ['q7_nature_env', 'q5_business'],
    'GREEN TECHNOLOGY': ['q7_nature_env', 'q9_innovation', 'q1_science_tech'],
    'INFORMATION SYSTEMS': ['q4_data', 'q1_science_tech', 'q5_business'],
    'LANDSCAPE': ['q3_design', 'q7_nature_env'],
    'TRANSLATION': ['q6_arts_culture', 'q12_flexible_path', 'q10_people_social'],
    'SOFTWARE ENGINEERING': ['q1_science_tech', 'q4_data', 'q9_innovation'],
    'FILM': ['q6_arts_culture', 'q3_design', 'q9_innovation'],
    'PROJECT MANAGEMENT': ['q5_business', 'q12_flexible_path', 'q11_urban_corporate'],
    'ENGINEERING TECHNOLOGY': ['q1_science_tech', 'q8_hands_on', 'q9_innovation'],
    'BIOSYSTEMS TECHNOLOGY': ['q7_nature_env', 'q1_science_tech', 'q8_hands_on'],
    'COMMUNICATION': ['q6_arts_culture', 'q10_people_social'],
    'MASS MEDIA': ['q6_arts_culture', 'q10_people_social', 'q9_innovation'],
    'PERFORMING ARTS': ['q6_arts_culture', 'q12_flexible_path']
};

// Sri Lankan A/L Streams (6 streams as per UGC)
// 1. Physical Science
// 2. Biological Science  
// 3. Commerce
// 4. Arts
// 5. Engineering Technology (Technology Stream)
// 6. Bio Technology (Technology Stream)

// Stream eligibility based on UGC guidelines
const streamEligibility: Record<string, string[]> = {
    // Medical & Health Sciences - Biological Science only
    'MEDICINE': ['Biological Science'],
    'DENTAL SURGERY': ['Biological Science'],
    'VETERINARY SCIENCE': ['Biological Science'],
    'NURSING': ['Biological Science'],
    'PHARMACY': ['Biological Science'],
    'AYURVEDA': ['Biological Science'],
    'SIDDHA': ['Biological Science'],
    'UNANI': ['Biological Science'],
    'MEDICAL LABORATORY': ['Biological Science'],
    'RADIOGRAPHY': ['Biological Science'],
    'PHYSIOTHERAPY': ['Biological Science'],
    'HEALTH PROMOTION': ['Biological Science'],
    'SPEECH AND HEARING': ['Biological Science'],

    // Pure Sciences
    'BIOLOGICAL SCIENCE': ['Biological Science', 'Bio Technology'],
    'APPLIED SCIENCES (BIOLOGICAL': ['Biological Science', 'Bio Technology'],
    'PHYSICAL SCIENCE': ['Physical Science', 'Engineering Technology'],
    'APPLIED SCIENCES (PHYSICAL': ['Physical Science', 'Engineering Technology'],
    'BIOCHEMISTRY': ['Biological Science'],
    'STATISTICS': ['Physical Science'],

    // Agriculture & Environment
    'AGRICULTURE': ['Biological Science', 'Bio Technology'],
    'AGRICULTURAL': ['Biological Science', 'Bio Technology'],
    'AGRIBUSINESS': ['Biological Science', 'Bio Technology', 'Commerce'],
    'FOOD SCIENCE': ['Biological Science', 'Bio Technology'],
    'FOOD PRODUCTION': ['Biological Science', 'Bio Technology'],
    'ANIMAL': ['Biological Science', 'Bio Technology'],
    'FISHERIES': ['Biological Science', 'Bio Technology'],
    'AQUATIC': ['Biological Science', 'Bio Technology'],
    'EXPORT AGRICULTURE': ['Biological Science', 'Bio Technology'],
    'ENVIRONMENTAL': ['Biological Science', 'Physical Science', 'Bio Technology'],
    'GREEN TECHNOLOGY': ['Biological Science', 'Physical Science', 'Bio Technology', 'Engineering Technology'],

    // Engineering & Technology
    'ENGINEERING': ['Physical Science', 'Engineering Technology'],
    'QUANTITY SURVEYING': ['Physical Science', 'Engineering Technology'],
    'SURVEYING': ['Physical Science', 'Engineering Technology'],
    'ARCHITECTURE': ['Physical Science', 'Engineering Technology', 'Arts'],
    'LANDSCAPE': ['Physical Science', 'Engineering Technology', 'Arts'],
    'URBAN': ['Physical Science', 'Engineering Technology'],
    'FACILITIES MANAGEMENT': ['Physical Science', 'Engineering Technology', 'Commerce'],
    'TRANSPORT': ['Physical Science', 'Engineering Technology'],
    'MINERAL RESOURCES': ['Physical Science', 'Engineering Technology'],

    // Computer Science & IT
    'COMPUTER SCIENCE': ['Physical Science', 'Engineering Technology'],
    'SOFTWARE ENGINEERING': ['Physical Science', 'Engineering Technology'],
    'INFORMATION TECHNOLOGY': ['Physical Science', 'Engineering Technology', 'Commerce'],
    'ICT': ['Physical Science', 'Engineering Technology', 'Commerce'],
    'INFORMATION SYSTEMS': ['Physical Science', 'Engineering Technology', 'Commerce'],
    'INDUSTRIAL INFORMATION': ['Physical Science', 'Biological Science', 'Engineering Technology', 'Bio Technology'],
    'BUSINESS INFORMATION': ['Physical Science', 'Commerce', 'Engineering Technology'],

    // Technology Stream Degrees
    'BIOSYSTEMS TECHNOLOGY': ['Bio Technology', 'Biological Science'],
    'ENGINEERING TECHNOLOGY': ['Engineering Technology', 'Physical Science'],
    'SCIENCE AND TECHNOLOGY': ['Physical Science', 'Biological Science', 'Engineering Technology', 'Bio Technology'],

    // Management & Commerce - Multiple streams eligible
    'MANAGEMENT': ['Physical Science', 'Biological Science', 'Commerce', 'Arts', 'Engineering Technology', 'Bio Technology'],
    'COMMERCE': ['Commerce', 'Physical Science', 'Biological Science', 'Arts'],
    'REAL ESTATE': ['Physical Science', 'Commerce', 'Engineering Technology'],
    'ENTREPRENEURSHIP': ['Physical Science', 'Biological Science', 'Commerce', 'Arts', 'Engineering Technology', 'Bio Technology'],
    'PROJECT MANAGEMENT': ['Physical Science', 'Commerce', 'Engineering Technology'],
    'HOSPITALITY': ['Commerce', 'Arts', 'Physical Science', 'Biological Science'],
    'TOURISM': ['Commerce', 'Arts', 'Physical Science', 'Biological Science'],

    // Arts & Humanities
    'ARTS': ['Arts', 'Commerce'],
    'LAW': ['Arts', 'Commerce', 'Physical Science', 'Biological Science'],
    'PEACE AND CONFLICT': ['Arts'],
    'TRANSLATION': ['Arts'],
    'ISLAMIC STUDIES': ['Arts'],
    'ARABIC': ['Arts'],
    'COMMUNICATION': ['Arts', 'Commerce'],
    'MASS MEDIA': ['Arts', 'Commerce'],

    // Visual & Performing Arts - All streams with aptitude test
    'DESIGN': ['Physical Science', 'Arts', 'Engineering Technology'],
    'FASHION': ['Physical Science', 'Arts', 'Engineering Technology'],
    'MUSIC': ['Arts', 'Commerce', 'Physical Science', 'Biological Science'],
    'DANCE': ['Arts', 'Commerce', 'Physical Science', 'Biological Science'],
    'DRAMA': ['Arts', 'Commerce', 'Physical Science', 'Biological Science'],
    'VISUAL': ['Arts', 'Physical Science'],
    'PERFORMING ARTS': ['Arts', 'Commerce', 'Physical Science', 'Biological Science'],
    'FILM': ['Arts', 'Commerce'],
    'ART & DESIGN': ['Arts', 'Physical Science'],

    // Sports & Physical Education - Multiple streams with aptitude test
    'PHYSICAL EDUCATION': ['Physical Science', 'Biological Science', 'Arts', 'Commerce', 'Engineering Technology', 'Bio Technology'],
    'SPORTS': ['Physical Science', 'Biological Science', 'Arts', 'Commerce', 'Engineering Technology', 'Bio Technology']
};

// Raw course data
const rawCourseData = `MEDICINE,UNIVERSITY OF COLOMBO,001A
MEDICINE,UNIVERSITY OF PERADENIYA,001B
MEDICINE,UNIVERSITY OF SRI JAYEWARDENEPURA,001C
MEDICINE,UNIVERSITY OF KELANIYA,001D
MEDICINE,UNIVERSITY OF JAFFNA,001E
MEDICINE,UNIVERSITY OF RUHUNA,001F
MEDICINE,UNIVERSITY OF MORATUWA,001G
MEDICINE,EASTERN UNIVERSITY SRI LANKA,001H
MEDICINE,RAJARATA UNIVERSITY OF SRI LANKA,001K
MEDICINE,SABARAGAMUWA UNIVERSITY OF SRI LANKA,001L
MEDICINE,WAYAMBA UNIVERSITY OF SRI LANKA,001M
MEDICINE,UVA WELLASSA UNIVERSITY OF SRI LANKA,001U
DENTAL SURGERY,UNIVERSITY OF PERADENIYA,002B
DENTAL SURGERY,UNIVERSITY OF SRI JAYEWARDENEPURA,002C
VETERINARY SCIENCE,UNIVERSITY OF PERADENIYA,003B
AGRICULTURE,UNIVERSITY OF JAFFNA,004E
AGRICULTURE,EASTERN UNIVERSITY SRI LANKA,004H
AGRICULTURE,RAJARATA UNIVERSITY OF SRI LANKA,004K
AGRICULTURE,SABARAGAMUWA UNIVERSITY OF SRI LANKA,004L
AGRICULTURE,WAYAMBA UNIVERSITY OF SRI LANKA,004M
FOOD SCIENCE & NUTRITION,WAYAMBA UNIVERSITY OF SRI LANKA,005M
BIOLOGICAL SCIENCE,UNIVERSITY OF COLOMBO,006A
BIOLOGICAL SCIENCE,UNIVERSITY OF PERADENIYA,006B
BIOLOGICAL SCIENCE,UNIVERSITY OF SRI JAYEWARDENEPURA,006C
BIOLOGICAL SCIENCE,UNIVERSITY OF KELANIYA,006D
BIOLOGICAL SCIENCE,UNIVERSITY OF JAFFNA,006E
BIOLOGICAL SCIENCE,UNIVERSITY OF RUHUNA,006F
BIOLOGICAL SCIENCE,EASTERN UNIVERSITY SRI LANKA,006H
BIOLOGICAL SCIENCE,SOUTH EASTERN UNIVERSITY OF SRI LANKA,006J
APPLIED SCIENCES (BIOLOGICAL SC.),RAJARATA UNIVERSITY OF SRI LANKA,007K
APPLIED SCIENCES (BIOLOGICAL SC.),SABARAGAMUWA UNIVERSITY OF SRI LANKA,007L
APPLIED SCIENCES (BIOLOGICAL SC.),UNIVERSITY OF VAVUNIYA SRI LANKA,007R
ENGINEERING,UNIVERSITY OF PERADENIYA,008B
ENGINEERING,UNIVERSITY OF SRI JAYEWARDENEPURA,008C
ENGINEERING,UNIVERSITY OF JAFFNA,008E
ENGINEERING,UNIVERSITY OF RUHUNA,008F
ENGINEERING,UNIVERSITY OF MORATUWA,008G
ENGINEERING,SOUTH EASTERN UNIVERSITY OF SRI LANKA,008J
ENGINEERING (EM),UNIVERSITY OF MORATUWA,009G
ENGINEERING (TM),UNIVERSITY OF MORATUWA,010G
QUANTITY SURVEYING,UNIVERSITY OF MORATUWA,011G
COMPUTER SCIENCE,UNIVERSITY OF SRI JAYEWARDENEPURA,012C
COMPUTER SCIENCE,UNIVERSITY OF KELANIYA,012D
COMPUTER SCIENCE,UNIVERSITY OF JAFFNA,012E
COMPUTER SCIENCE,UNIVERSITY OF RUHUNA,012F
COMPUTER SCIENCE,UNIVERSITY OF COLOMBO SCHOOL OF COMPUTING,012T
COMPUTER SCIENCE,TRINCOMALEE CAMPUS EASTERN UNIVERSITY SRI LANKA,012W
PHYSICAL SCIENCE,UNIVERSITY OF COLOMBO,013A
PHYSICAL SCIENCE,UNIVERSITY OF PERADENIYA,013B
PHYSICAL SCIENCE,UNIVERSITY OF SRI JAYEWARDENEPURA,013C
PHYSICAL SCIENCE,UNIVERSITY OF KELANIYA,013D
PHYSICAL SCIENCE,UNIVERSITY OF JAFFNA,013E
PHYSICAL SCIENCE,UNIVERSITY OF RUHUNA,013F
PHYSICAL SCIENCE,EASTERN UNIVERSITY SRI LANKA,013H
PHYSICAL SCIENCE,SOUTH EASTERN UNIVERSITY OF SRI LANKA,013J
SURVEYING SCIENCE,SABARAGAMUWA UNIVERSITY OF SRI LANKA,014L
APPLIED SCIENCES (PHYSICAL SC.),RAJARATA UNIVERSITY OF SRI LANKA,015K
APPLIED SCIENCES (PHYSICAL SC.),SABARAGAMUWA UNIVERSITY OF SRI LANKA,015L
APPLIED SCIENCES (PHYSICAL SC.),WAYAMBA UNIVERSITY OF SRI LANKA,015M
APPLIED SCIENCES (PHYSICAL SC.),UNIVERSITY OF VAVUNIYA SRI LANKA,015R
APPLIED SCIENCES (PHYSICAL SC.),TRINCOMALEE CAMPUS EASTERN UNIVERSITY SRI LANKA,015W
MANAGEMENT,UNIVERSITY OF COLOMBO,016A
MANAGEMENT,UNIVERSITY OF PERADENIYA,016B
MANAGEMENT,UNIVERSITY OF SRI JAYEWARDENEPURA,016C
MANAGEMENT,UNIVERSITY OF KELANIYA,016D
MANAGEMENT,UNIVERSITY OF JAFFNA,016E
MANAGEMENT,UNIVERSITY OF RUHUNA,016F
MANAGEMENT,EASTERN UNIVERSITY SRI LANKA,016H
MANAGEMENT,SOUTH EASTERN UNIVERSITY OF SRI LANKA,016J
MANAGEMENT,RAJARATA UNIVERSITY OF SRI LANKA,016K
MANAGEMENT,SABARAGAMUWA UNIVERSITY OF SRI LANKA,016L
MANAGEMENT,WAYAMBA UNIVERSITY OF SRI LANKA,016M
REAL ESTATE MANAGEMENT AND VALUATION,UNIVERSITY OF SRI JAYEWARDENEPURA,017C
COMMERCE,UNIVERSITY OF SRI JAYEWARDENEPURA,018C
COMMERCE,UNIVERSITY OF KELANIYA,018D
COMMERCE,UNIVERSITY OF JAFFNA,018E
COMMERCE,EASTERN UNIVERSITY SRI LANKA,018H
COMMERCE,SOUTH EASTERN UNIVERSITY OF SRI LANKA,018J
ARTS,UNIVERSITY OF COLOMBO,019A
ARTS,UNIVERSITY OF PERADENIYA,019B
ARTS,UNIVERSITY OF SRI JAYEWARDENEPURA,019C
ARTS,UNIVERSITY OF KELANIYA,019D
ARTS,UNIVERSITY OF JAFFNA,019E
ARTS,UNIVERSITY OF RUHUNA,019F
ARTS,EASTERN UNIVERSITY SRI LANKA,019H
ARTS,SOUTH EASTERN UNIVERSITY OF SRI LANKA,019J
ARTS,RAJARATA UNIVERSITY OF SRI LANKA,019K
ARTS (SP) - MASS MEDIA,SRIPALEE CAMPUS UNIVERSITY OF COLOMBO,020S
ARTS (SP) - PERFORMING ARTS,SRIPALEE CAMPUS UNIVERSITY OF COLOMBO,041S
ARTS (SAB),SABARAGAMUWA UNIVERSITY OF SRI LANKA,021L
MANAGEMENT STUDIES (TV),TRINCOMALEE CAMPUS EASTERN UNIVERSITY SRI LANKA,022W
MANAGEMENT STUDIES (TV),UNIVERSITY OF VAVUNIYA SRI LANKA,022R
ARCHITECTURE,UNIVERSITY OF MORATUWA,023G
DESIGN,UNIVERSITY OF MORATUWA,024G
LAW,UNIVERSITY OF COLOMBO,025A
LAW,UNIVERSITY OF PERADENIYA,025B
LAW,UNIVERSITY OF JAFFNA,025E
INFORMATION TECHNOLOGY (IT),UNIVERSITY OF MORATUWA,026G
MANAGEMENT AND INFORMATION TECHNOLOGY (MIT),UNIVERSITY OF KELANIYA,027D
MANAGEMENT AND PUBLIC POLICY,UNIVERSITY OF SRI JAYEWARDENEPURA,028C
COMMUNICATION STUDIES,TRINCOMALEE CAMPUS EASTERN UNIVERSITY SRI LANKA,029W
URBAN INFORMATICS AND PLANNING,UNIVERSITY OF MORATUWA,030G
PEACE AND CONFLICT RESOLUTION,UNIVERSITY OF KELANIYA,031D
AYURVEDA MEDICINE AND SURGERY,UNIVERSITY OF COLOMBO,032A
AYURVEDA MEDICINE AND SURGERY,GAMPAHA WICKRAMARACHCHI UNIVERSITY OF INDIGENOUS MEDICINE SRI LANKA,032P
UNANI MEDICINE AND SURGERY,UNIVERSITY OF COLOMBO,033A
FASHION DESIGN & PRODUCT DEVELOPMENT,UNIVERSITY OF MORATUWA,034G
FOOD SCIENCE & TECHNOLOGY,UNIVERSITY OF PERADENIYA,035B
FOOD SCIENCE & TECHNOLOGY,UNIVERSITY OF SRI JAYEWARDENEPURA,035C
FOOD SCIENCE & TECHNOLOGY,SABARAGAMUWA UNIVERSITY OF SRI LANKA,035L
SIDDHA MEDICINE AND SURGERY,UNIVERSITY OF JAFFNA,036E
SIDDHA MEDICINE AND SURGERY,TRINCOMALEE CAMPUS EASTERN UNIVERSITY SRI LANKA,036W
NURSING,UNIVERSITY OF COLOMBO,037A
NURSING,UNIVERSITY OF PERADENIYA,037B
NURSING,UNIVERSITY OF SRI JAYEWARDENEPURA,037C
NURSING,UNIVERSITY OF JAFFNA,037E
NURSING,UNIVERSITY OF RUHUNA,037F
NURSING,EASTERN UNIVERSITY SRI LANKA,037H
INFORMATION AND COMMUNICATION TECHNOLOGY (ICT),RAJARATA UNIVERSITY OF SRI LANKA,038K
INFORMATION AND COMMUNICATION TECHNOLOGY (ICT),UNIVERSITY OF VAVUNIYA SRI LANKA,038R
AGRICULTURAL TECHNOLOGY & MANAGEMENT,UNIVERSITY OF PERADENIYA,039B
HEALTH PROMOTION,RAJARATA UNIVERSITY OF SRI LANKA,050K
PHARMACY,UNIVERSITY OF PERADENIYA,051B
PHARMACY,UNIVERSITY OF SRI JAYEWARDENEPURA,051C
PHARMACY,UNIVERSITY OF JAFFNA,051E
PHARMACY,UNIVERSITY OF RUHUNA,051F
MEDICAL LABORATORY SCIENCES,UNIVERSITY OF PERADENIYA,052B
MEDICAL LABORATORY SCIENCES,UNIVERSITY OF SRI JAYEWARDENEPURA,052C
MEDICAL LABORATORY SCIENCES,UNIVERSITY OF JAFFNA,052E
MEDICAL LABORATORY SCIENCES,UNIVERSITY OF RUHUNA,052F
RADIOGRAPHY,UNIVERSITY OF PERADENIYA,053B
PHYSIOTHERAPY,UNIVERSITY OF COLOMBO,054A
PHYSIOTHERAPY,UNIVERSITY OF PERADENIYA,054B
ENVIRONMENTAL CONSERVATION & MANAGEMENT,UNIVERSITY OF KELANIYA,055D
FACILITIES MANAGEMENT,UNIVERSITY OF MORATUWA,056G
TRANSPORT MANAGEMENT & LOGISTICS ENGINEERING (TMLE),UNIVERSITY OF MORATUWA,057G
BIOCHEMISTRY & MOLECULAR BIOLOGY,UNIVERSITY OF COLOMBO,058A
INDUSTRIAL STATISTICS & MATHEMATICAL FINANCE,UNIVERSITY OF COLOMBO,059A
STATISTICS & OPERATIONS RESEARCH,UNIVERSITY OF PERADENIYA,060B
FISHERIES & MARINE SCIENCES,UNIVERSITY OF RUHUNA,062F
ISLAMIC STUDIES,SOUTH EASTERN UNIVERSITY OF SRI LANKA,063J
SCIENCE AND TECHNOLOGY,UVA WELLASSA UNIVERSITY OF SRI LANKA,064U
COMPUTER SCIENCE & TECHNOLOGY,UVA WELLASSA UNIVERSITY OF SRI LANKA,065U
ENTREPRENEURSHIP AND MANAGEMENT,UVA WELLASSA UNIVERSITY OF SRI LANKA,066U
ANIMAL PRODUCTION AND FOOD TECHNOLOGY,UVA WELLASSA UNIVERSITY OF SRI LANKA,067U
MUSIC,UNIVERSITY OF SRI JAYEWARDENEPURA,068C
MUSIC,UNIVERSITY OF JAFFNA,068E
MUSIC,SWAMY VIPULANANDA INSTITUTE OF AESTHETIC STUDIES EASTERN UNIVERSITY SRI LANKA,068Y
MUSIC,UNIVERSITY OF THE VISUAL & PERFORMING ARTS,068Z
DANCE,UNIVERSITY OF JAFFNA,069E
DANCE,SWAMY VIPULANANDA INSTITUTE OF AESTHETIC STUDIES EASTERN UNIVERSITY SRI LANKA,069Y
DANCE,UNIVERSITY OF THE VISUAL & PERFORMING ARTS,069Z
ART & DESIGN,UNIVERSITY OF JAFFNA,070E
DRAMA & THEATRE,SWAMY VIPULANANDA INSTITUTE OF AESTHETIC STUDIES EASTERN UNIVERSITY SRI LANKA,071Y
DRAMA & THEATRE,UNIVERSITY OF THE VISUAL & PERFORMING ARTS,071Z
VISUAL & TECHNOLOGICAL ARTS,SWAMY VIPULANANDA INSTITUTE OF AESTHETIC STUDIES EASTERN UNIVERSITY SRI LANKA,072Y
EXPORT AGRICULTURE,UVA WELLASSA UNIVERSITY OF SRI LANKA,073U
INDUSTRIAL INFORMATION TECHNOLOGY,UVA WELLASSA UNIVERSITY OF SRI LANKA,075U
MINERAL RESOURCES AND TECHNOLOGY,UVA WELLASSA UNIVERSITY OF SRI LANKA,076U
BUSINESS INFORMATION SYSTEMS (HONOURS) (BIS),UNIVERSITY OF SRI JAYEWARDENEPURA,077C
MANAGEMENT AND INFORMATION TECHNOLOGY (SEUSL),SOUTH EASTERN UNIVERSITY OF SRI LANKA,079J
PHYSICAL EDUCATION,UNIVERSITY OF JAFFNA,081E
PHYSICAL EDUCATION,SABARAGAMUWA UNIVERSITY OF SRI LANKA,081L
SPORTS SCIENCE & MANAGEMENT,UNIVERSITY OF SRI JAYEWARDENEPURA,082C
SPORTS SCIENCE & MANAGEMENT,UNIVERSITY OF KELANIYA,082D
SPORTS SCIENCE & MANAGEMENT,SABARAGAMUWA UNIVERSITY OF SRI LANKA,082L
SPEECH AND HEARING SCIENCES,UNIVERSITY OF KELANIYA,083D
ARABIC LANGUAGE,SOUTH EASTERN UNIVERSITY OF SRI LANKA,084J
VISUAL ARTS,UNIVERSITY OF THE VISUAL & PERFORMING ARTS,085Z
ANIMAL SCIENCE & FISHERIES,UNIVERSITY OF PERADENIYA,086B
FOOD PRODUCTION & TECHNOLOGY MANAGEMENT,WAYAMBA UNIVERSITY OF SRI LANKA,087M
AQUATIC RESOURCES TECHNOLOGY,UVA WELLASSA UNIVERSITY OF SRI LANKA,088U
HOSPITALITY TOURISM AND EVENTS MANAGEMENT,UVA WELLASSA UNIVERSITY OF SRI LANKA,090U
INFORMATION TECHNOLOGY & MANAGEMENT,UNIVERSITY OF MORATUWA,091G
TOURISM & HOSPITALITY MANAGEMENT,RAJARATA UNIVERSITY OF SRI LANKA,092K
TOURISM & HOSPITALITY MANAGEMENT,SABARAGAMUWA UNIVERSITY OF SRI LANKA,092L
AGRICULTURAL RESOURCE MANAGEMENT AND TECHNOLOGY,UNIVERSITY OF RUHUNA,093F
AGRIBUSINESS MANAGEMENT,UNIVERSITY OF RUHUNA,094F
GREEN TECHNOLOGY,UNIVERSITY OF RUHUNA,095F
INFORMATION SYSTEMS,UNIVERSITY OF SRI JAYEWARDENEPURA,096C
INFORMATION SYSTEMS,SABARAGAMUWA UNIVERSITY OF SRI LANKA,096L
INFORMATION SYSTEMS,UNIVERSITY OF COLOMBO SCHOOL OF COMPUTING,096T
LANDSCAPE ARCHITECTURE,UNIVERSITY OF MORATUWA,097G
TRANSLATION STUDIES,UNIVERSITY OF KELANIYA,098D
TRANSLATION STUDIES,UNIVERSITY OF JAFFNA,098E
TRANSLATION STUDIES,EASTERN UNIVERSITY SRI LANKA,098H
TRANSLATION STUDIES,SABARAGAMUWA UNIVERSITY OF SRI LANKA,098L
SOFTWARE ENGINEERING,UNIVERSITY OF SRI JAYEWARDENEPURA,099C
SOFTWARE ENGINEERING,UNIVERSITY OF KELANIYA,099D
SOFTWARE ENGINEERING,SABARAGAMUWA UNIVERSITY OF SRI LANKA,099L
FILM & TELEVISION STUDIES,UNIVERSITY OF KELANIYA,100D
PROJECT MANAGEMENT,UNIVERSITY OF VAVUNIYA SRI LANKA,101R
ENGINEERING TECHNOLOGY (ET),UNIVERSITY OF COLOMBO,102A
ENGINEERING TECHNOLOGY (ET),UNIVERSITY OF SRI JAYEWARDENEPURA,102C
ENGINEERING TECHNOLOGY (ET),UNIVERSITY OF KELANIYA,102D
ENGINEERING TECHNOLOGY (ET),UNIVERSITY OF JAFFNA,102E
ENGINEERING TECHNOLOGY (ET),UNIVERSITY OF RUHUNA,102F
ENGINEERING TECHNOLOGY (ET),RAJARATA UNIVERSITY OF SRI LANKA,102K
ENGINEERING TECHNOLOGY (ET),SABARAGAMUWA UNIVERSITY OF SRI LANKA,102L
ENGINEERING TECHNOLOGY (ET),WAYAMBA UNIVERSITY OF SRI LANKA,102M
ENGINEERING TECHNOLOGY (ET),UVA WELLASSA UNIVERSITY OF SRI LANKA,102U
BIOSYSTEMS TECHNOLOGY (BST),UNIVERSITY OF COLOMBO,103A
BIOSYSTEMS TECHNOLOGY (BST),UNIVERSITY OF SRI JAYEWARDENEPURA,103C
BIOSYSTEMS TECHNOLOGY (BST),UNIVERSITY OF KELANIYA,103D
BIOSYSTEMS TECHNOLOGY (BST),UNIVERSITY OF JAFFNA,103E
BIOSYSTEMS TECHNOLOGY (BST),UNIVERSITY OF RUHUNA,103F
BIOSYSTEMS TECHNOLOGY (BST),EASTERN UNIVERSITY SRI LANKA,103H
BIOSYSTEMS TECHNOLOGY (BST),SOUTH EASTERN UNIVERSITY OF SRI LANKA,103J
BIOSYSTEMS TECHNOLOGY (BST),RAJARATA UNIVERSITY OF SRI LANKA,103K
BIOSYSTEMS TECHNOLOGY (BST),SABARAGAMUWA UNIVERSITY OF SRI LANKA,103L
BIOSYSTEMS TECHNOLOGY (BST),WAYAMBA UNIVERSITY OF SRI LANKA,103M
BIOSYSTEMS TECHNOLOGY (BST),UVA WELLASSA UNIVERSITY OF SRI LANKA,103U`;

// Parse course data
export function parseCourseData(): UGCCourse[] {
    return rawCourseData.split('\n').map(line => {
        const [courseName, university, uniCode] = line.split(',');
        const interests = getInterestMapping(courseName);
        const streams = getStreamEligibility(courseName);
        return {
            courseName: courseName.trim(),
            university: university.trim(),
            uniCode: uniCode.trim(),
            requiresAptitudeTest: aptitudeTestCodes.has(uniCode.trim()),
            eligibleStreams: streams,
            interestMapping: interests
        };
    });
}

function getInterestMapping(courseName: string): string[] {
    const upperName = courseName.toUpperCase();
    for (const [key, interests] of Object.entries(courseInterestMap)) {
        if (upperName.includes(key)) return interests;
    }
    return ['q12_flexible_path'];
}

function getStreamEligibility(courseName: string): string[] {
    const upperName = courseName.toUpperCase();
    for (const [key, streams] of Object.entries(streamEligibility)) {
        if (upperName.includes(key)) return streams;
    }
    return ['Physical Science', 'Biological Science', 'Commerce', 'Arts', 'Engineering Technology', 'Bio Technology'];
}

export const ugcCourses = parseCourseData();
